parameters:
    kushki_public_id: '%env(KUSHKI_PUBLIC_ID)%'
    kushki_private_id: '%env(KUSHKI_PRIVATE_ID)%'
    kushki_is_dev: '%env(bool:KUSHKI_IS_DEV)%'
    kushki_lang: '%env(const:KUSHKI_LANG)%'
    kushki_currency: '%env(const:KUSHKI_CURRENCY)%'
    env(KUSHKI_PUBLIC_ID): 'YOUR-KUSHKI-PUBLIC-ID'
    env(KUSHKI_PRIVATE_ID): 'YOUR-KUSHKI-PRIVATE-ID'
    env(KUSHKI_LANG): 'kushki\lib\KushkiLanguage::ES'
    env(KUSHKI_CURRENCY): 'kushki\lib\KushkiCurrency::COP'
    env(KUSHKI_IS_DEV): 'true'

services:
    _defaults:
        public: false

    #SERVICES
    MiguelAlcaino\KushkiBundle\Service\KushkiFactory:
    kushki:
        class: kushki\lib\Kushki:
        factory: 'MiguelAlcaino\KushkiBundle\Service\KushkiFactory:create'
        arguments:
            - '%kushki_private_id%'
            - '%kushki_lang%'
            - '%kushki_currency%'
            - '%kushki_is_dev%'
    miguelalcaino.kushki.service:
        class: MiguelAlcaino\KushkiBundle\Service\KushkiService
        arguments:
            $kushki: '@kushki'
    MiguelAlcaino\KushkiBundle\Service\KushkiService: '@miguelalcaino.kushki.service'